version: '1.0.0'
volumes:

services:

  db:
    container_name: pg_container
    image: postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookazikos_production

    restart: unless-stopped
    volumes:
        - node_data:/var/lib/postgresql/data

  bookazikos-node-js:
    image: bookazikos-node-js
    environment:
      PG_USER: admin
      PG_PASSWORD: postgres
      PG_HOST: db
    depends_on:
        - db
    ports:
        - "6950:6950"
    volumes:
          - node_data:/var/lib/postgresql/data
    command: [ "npm","run","prep-db-prod"]

volumes:
        node_data: {}
