services:
  db:
    container_name: pg_container
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookazikos_development
    ports:
      - "5432:5432"
  bookazikos-node-js:
    build: bookazikos-node-js
    depends_on:
        - db
    ports:
        - "3000:3000"
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "server.js"]
