version: '1.0.0'

volumes:
        node_data: {}


services:

  certbot:
    image: certbot/certbot
    container_name: certbot
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email owencoogan01@live.fr -d crece-en-libertad.owensapi.com --agree-tos --no-eff-email
  db:
    container_name: pg_container
    image: postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookazikos_production

    restart: unless-stopped
    volumes:
        - node_data:/var/lib/postgresql/data


  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - node_data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot

    depends_on:
      - bookazikos-node-js


  bookazikos-node-js:
    image: bookazikos-node-js
    environment:
      PG_USER: admin
      PG_PASSWORD: postgres
      PG_HOST: db
    depends_on:
        - db
    ports:
        - "6950:6950"
    volumes:
          - node_data:/var/lib/postgresql/data
    command: [ "npm","run","prep-db-prod"]


