services:
  db:
    container_name: pg_container
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookazikos_production
    ports:
      - "5432:5432"
