version: '1.0.0'

volumes:
        node_data: {}
        certbot-etc:
        certbot-var:
        web-root:
          driver: local
          driver_opts:
            type: none
            o: bind
            device: "node_data"


services:

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - webserver
    command: >-
             certonly --reinstall --webroot -w /var/www/html
             --email owencoogan01@gmail.com --agree-tos --no-eff-email
             -d www.crece-en-libertad.owensapi.com
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
  db:
    container_name: pg_container
    image: postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookazikos_production

    restart: unless-stopped
    volumes:
        - node_data:/var/lib/postgresql/data


  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - node_data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - bookazikos-node-js


  bookazikos-node-js:
    image: bookazikos-node-js
    environment:
      PG_USER: admin
      PG_PASSWORD: postgres
      PG_HOST: db
    depends_on:
        - db
    ports:
        - "6950:6950"
    volumes:
          - node_data:/var/lib/postgresql/data
    command: [ "npm","run","prep-db-prod"]


