services:
  db:
    container_name: pg_container
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookazikos_development
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
