services:
  db:
    container_name: pg_container
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookazikos_production
    ports:
      - "5432:5432"

  bookazikos-node-js:
    image: bookazikos-node-js:latest
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    build:
      dockerfile
    depends_on:
      - db
    volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules
    ports:
      - "6950:6950"
